### ISSUE TITLE
获取 apk 信息时出错

### ISSUE THREAD

**Issue by tastypear** [bihe0832/AndroidGetAPKInfo#1]
get channel and apkinfo failed, throw an Exception
sample:
https://pan.baidu.com/s/1i5Hwjpr 2828

**Comment by bihe0832** [comment]
用你提供的apk测试了一下，确实存在异常，异常位置是在将AndroidMainFest从二进制转化为xml的过程（AXMLPrinter.java）。测试安装发现可以正常安装，因此问题的原因还要后面详细看下。

解析AndroidMainFest使用的是官方提供的库，但是目前这个库已经不维护了，后面找时间我看看有没有新的库。

**Comment by bihe0832** [comment]
最新的master或者[v1.2.0](https://github.com/bihe0832/Android-GetAPKInfo/releases/tag/v1.2.0) 下均为已经修复后的版本。个人验证范围有限，麻烦大家验证确认下~
