### ISSUE TITLE
使用CheckAndroidSignature.jar检查一个605MB的apk签名信息，需要10多秒时间，能提高下执行效率吗？

### ISSUE THREAD

**Issue by Bingoliallen** [bihe0832/AndroidGetAPKInfo#10]
比如我只需要得到是否签名或者是否是V2签名，是否可以帮助到减少执行时间？

**Comment by bihe0832** [comment]
你好，目前所有代码都已经开源了，如果你只想检查是否签名或者是否是V2签名，可以直接修改下面的文件并重新生成Jar即可，所有对于V1，V2，V3的检查都在这个文件：

CheckAndroidSignatureByAPKSig/src/main/java/com/android/apksigner/ApkSignerTool.java
