### ISSUE TITLE
Could you tell me how to quickly import source code to generate new jar?

### ISSUE THREAD

**Issue by huangjiange** [bihe0832/AndroidGetAPKInfo#4]
I want to modify some code to test.
I used AndroidStudio to import this source code but can not compile directly.
Please tell me how you build these source code and what ide you use?
Thank you very much.

**Comment by bihe0832** [comment]
1. I use Eclipse to build these source to jar
2. You can get how to build runnable jar in  this blog :[http://blog.bihe0832.com/runnable-jar.html](http://blog.bihe0832.com/runnable-jar.html)

**Comment by bihe0832** [comment]
http://blog.bihe0832.com/as-runnable-jar.html

**Comment by bihe0832** [comment]
http://blog.bihe0832.com/as-runnable-jar.html

This blog maybe useful for u to get how to quickly import source code to generate new jar.

**Comment by huangjiange** [comment]
Thanks a lot! I will find some time to try on it.
