### ISSUE TITLE
将控制台输出用JDBC写进数据库

### ISSUE THREAD

**Issue by Bill-11** [bihe0832/AndroidGetAPKInfo#8]
我试了一下在main函数里面改代码 发现控制台输出依旧没变 想问一下如果想自己实现上述操作的话得在哪改.

**Comment by bihe0832** [comment]
应该是运行分方式不对，可以按下面的方法运行

![image](https://user-images.githubusercontent.com/830993/98495709-c87e3180-227a-11eb-95a3-70c1c61ebd3c.png)

或者参考文章：https://blog.bihe0832.com/as-runnable-jar.html
