### ISSUE TITLE
反馈,解析apk信息,未关闭流,导致apk文件被占用无法删除

### ISSUE THREAD

**Issue by stars-one** [bihe0832/AndroidGetAPKInfo#9]
如题,在`ApkUtil.getApkInfo()`方法里,**那个InputStream流没有关闭**,加个finally关闭就可以了...

我这边整的上传,排查了好久才发现是这个占用了文件....

**Comment by bihe0832** [comment]
收到，因为之前都只是用于命令行问题定位，没有注意这些细节，感谢反馈，我尽快修复

**Comment by bihe0832** [comment]
V2.0.2 已修复
